### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 1357209470** [SplashCodes/JAViewer#118]
Build version: 1.3.5 
Build date: 1979-11-30 00:00:00 
Current date: 2018-01-01 23:23:41 
Device: OnePlus A0001 
 
Stack trace:  
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 524260 bytes
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3810)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: android.os.TransactionTooLargeException: data parcel size 524260 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:615)
	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3636)
	at a

**Comment by 1357209470** [comment]
Build version: 1.3.5 
Build date: 1979-11-30 00:00:00 
Current date: 2018-01-02 10:18:57 
Device: OnePlus A0001 
 
Stack trace:  
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 524260 bytes
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3810)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: android.os.TransactionTooLargeException: data parcel size 524260 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:615)
	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3636)
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3802)
	... 7 more

**Comment by 1357209470** [comment]
Build version: 1.3.5 
Build date: 1979-11-30 00:00:00 
Current date: 2018-01-07 22:16:00 
Device: OnePlus A0001 
 
Stack trace:  
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 523828 bytes
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3810)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: android.os.TransactionTooLargeException: data parcel size 523828 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:615)
	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3636)
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3802)
	... 7 more

**Comment by itabxt** [comment]
TransactionTooLargeException
