### ISSUE TITLE
收藏夹的问题和建议

### ISSUE THREAD

**Issue by kuanlaosiji** [SplashCodes/JAViewer#127]
收藏的影片和女优都被清除了 而且三次了 已排除我手机问题 希望能邮箱+密码登录保存收藏 还有不点开GitHub都不知道能反馈 希望在软件内部增加反馈 谢谢！

**Comment by kuanlaosiji** [comment]
Build version: 1.3.5 
Build date: 1979-11-30 00:00:00 
Current date: 2018-03-06 09:25:24 
Device: Xiaomi Redmi 3X 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.javiewer/io.github.javiewer.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'io.github.javiewer.adapter.item.DataSource io.github.javiewer.Configurations.getDataSource()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2423)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
	at android.app.ActivityThread.access$900(ActivityThread.java:153)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5441)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'io.github.javiewer.adapter.item.DataSource io.github.javiewer.Configurations.getDataSource()' on a null object reference
	at io.github.javiewer.JAViewer.getDataSource(JAViewer.java:64)
	at io.github.javiewer.JAViewer.recreateService(JAViewer.java:71)
	at io.github.javiewer.activity.MainActivity.onCreate(MainActivity.java:74)
	at android.app.Activity.performCreate(Activity.java:6303)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
	... 9 more

**Comment by SeanChengN** [comment]
JAViewer文件夹不要删掉就行了
