### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by kuanlaosiji** [SplashCodes/JAViewer#129]
Build version: 1.3.5 
Build date: 1979-11-30 00:00:00 
Current date: 2018-02-18 11:24:02 
Device: Xiaomi Redmi 3X 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.text()' on a null object reference
	at io.github.javiewer.network.provider.AVMOProvider.parseMoviesDetail(AVMOProvider.java:77)
	at io.github.javiewer.activity.MovieActivity$2.onResponse(MovieActivity.java:114)
	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5441)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

**Comment by DavisLandon** [comment]
闪退+1
Build version: 1.3.5 
Build date: 1979-11-30 00:00:00 
Current date: 2018-02-18 15:48:46 
Device: Xiaomi MI 5s Plus 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.text()' on a null object reference
	at io.github.javiewer.network.provider.AVMOProvider.parseMoviesDetail(AVMOProvider.java:77)
	at io.github.javiewer.activity.MovieActivity$2.onResponse(MovieActivity.java:114)
	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)

**Comment by SilenceContempt** [comment]
盼望作者快点修复

**Comment by younghang** [comment]
闪退加一，也是Element.text()' on a null object reference，翻墙之后点进去收藏夹就这样了

**Comment by 952371672** [comment]
我也是闪退

**Comment by 952371672** [comment]
Build version: 1.3.5 
Build date: 1979-11-30 00:00:00 
Current date: 2018-02-20 21:55:28 
Device: Xiaomi MI 6 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.text()' on a null object reference
	at io.github.javiewer.network.provider.AVMOProvider.parseMoviesDetail(AVMOProvider.java:77)
	at io.github.javiewer.activity.MovieActivity$2.onResponse(MovieActivity.java:114)
	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6365)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)

**Comment by ustgii** [comment]
我也是小米6，但是我没有闪退，用的是稳定版9.2系统

**Comment by 952371672** [comment]
我是9.2.4，不是打开就闪退，是看某些详情的时候闪退

**Comment by axiang137** [comment]
怎么下载apk
