### ISSUE TITLE
收藏夹Bug

### ISSUE THREAD

**Issue by SanbornWen** [SplashCodes/JAViewer#135]
Build version: 1.3.5 
Build date: 1979-11-30 00:00:00 
Current date: 2018-04-11 00:22:51 
Device: OnePlus A0001 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.text()' on a null object reference
	at io.github.javiewer.network.provider.AVMOProvider.parseMoviesDetail(AVMOProvider.java:77)
	at io.github.javiewer.activity.MovieActivity$2.onResponse(MovieActivity.java:114)
	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Comment by kuanlaosiji** [comment]
什么问题？

**Comment by SanbornWen** [comment]
收藏夹内容点击app崩溃问题
