### ISSUE TITLE
1.3.5崩溃

### ISSUE THREAD

**Issue by zs910208565** [SplashCodes/JAViewer#156]
Build version: 1.3.5 
Build date: 1979-11-30 00:00:00 
Current date: 2018-09-01 10:13:13 
Device: Xiaomi MI 6 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.text()' on a null object reference
	at io.github.javiewer.network.provider.AVMOProvider.parseMoviesDetail(AVMOProvider.java:77)
	at io.github.javiewer.activity.MovieActivity$2.onResponse(MovieActivity.java:114)
	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6365)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Comment by zs910208565** [comment]
日本无码源，有问题吧
