### ISSUE TITLE
经常报错

### ISSUE THREAD

**Issue by EV71** [SplashCodes/JAViewer#209]
Build version: 2.0.0-alpha 1 
Current date: 2018-12-11 00:27:39 
Device: Xiaomi Redmi Note 3 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.javiewer/io.github.javiewer.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'io.github.javiewer.adapter.item.DataSource io.github.javiewer.Configurations.getDataSource()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2489)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2551)
	at android.app.ActivityThread.access$1000(ActivityThread.java:169)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1432)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.app.ActivityThread.main(ActivityThread.java:5581)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:968)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:763)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'io.github.javiewer.adapter.item.DataSource io.github.javiewer.Configurations.getDataSource()' on a null object reference
	at io.github.javiewer.JAViewer.getDataSource(JAViewer.java:98)
	at io.github.javiewer.JAViewer.recreateService(JAViewer.java:103)
	at io.github.javiewer.activity.MainActivity.onCreate(MainActivity.java:101)
	at android.app.Activity.performCreate(Activity.java:6034)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1111)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2442)
	... 10 more

**Comment by itning** [comment]
The new version has solved this problem, please update to the latest version.

**Comment by EV71** [comment]
已经是最新版本啦
