### ISSUE TITLE
打开什么也没有了，收藏还有但是点开会报错

### ISSUE THREAD

**Issue by MIKULVJ** [SplashCodes/JAViewer#253]
Build version: 2.0.0-alpha 1 
Current date: 2019-04-27 01:38:45 
Device: HUAWEI BND-AL10 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.text()' on a null object reference
	at io.github.javiewer.network.provider.AVMOProvider.parseMoviesDetail(AVMOProvider.java:77)
	at io.github.javiewer.activity.MovieActivity$2.onResponse(MovieActivity.java:131)
	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:70)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:166)
	at android.app.ActivityThread.main(ActivityThread.java:7529)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by IAMOMGGOD** [comment]
我也是用不了我紅米4A

**Comment by Forbuger** [comment]
同样也是这个问题，好像是avmo的地址改了，有没有新地址啊？

**Comment by Yukino650** [comment]
一样的

**Comment by Bloodytomato** [comment]
是要凉了吗？_(:з」∠)_

**Comment by FRINHEN** [comment]
对啊，打开之后一片空白，什么都显示不出来！
