### ISSUE TITLE
1.3.1点击预览图片出现卡死的情况

### ISSUE THREAD

**Issue by 1357209470** [SplashCodes/JAViewer#52]
1.3.1点击预览图片出现卡死的情况

**Comment by SplashCodes** [comment]
暂未遇到该问题，1.3.2加入了崩溃后日志功能，请遇到该问题后复制并上传堆栈记录，以便我修复！

**Comment by 1357209470** [comment]
上传到这里吗，Build version: 1.3.2 
Build date: 1979-11-30 00:00:00 
Current date: 2017-05-09 20:03:26 
Device: OnePlus A0001 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.javiewer/io.github.javiewer.activity.GalleryActivity}: android.view.InflateException: Binary XML file line #15: Can't convert value at index 4 to dimension: type=0x4
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: android.view.InflateException: Binary XML file line #15: Can't convert value at index 4 to dimension: type=0x4
Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 4 to dimension: type=0x4
	at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:720)
	at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:7243)
	at android.widget.FrameLayout$LayoutParams.<init>(FrameLayout.java:439)
	at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:370)
	at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:369)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:860)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
	at io.github.javiewer.activity.GalleryActivity.onCreate(GalleryActivity.java:118)
	at android.app.Activity.performCreate(Activity.java:6684)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by 1357209470** [comment]
l出现问题的手机是 一加一（安卓7.1.2）另一个三星S6edge（安卓6.01）并未出现该问题

**Comment by 1357209470** [comment]
手机是 一加一（安卓7.1.2）

**Comment by SplashCodes** [comment]
感谢，已大致知道问题原因

**Comment by SplashCodes** [comment]
请试试[这个版本](http://javiewer-1253339046.cossh.myqcloud.com/JAViewer%201.3.2-beta1.apk)，是否布局正常且无略缩图浏览的崩溃问题

**Comment by SplashCodes** [comment]
@itsuha Please take a look.

**Comment by itsuha** [comment]
It works perfectly! Thanks for your kind help!

Sorry for the delay on replying.

**Comment by 1357209470** [comment]
安装大大您所提供的版本后问题已解决，感谢大大热心的帮助与无私的付出。谢谢
