### ISSUE TITLE
点击图片详情错误

### ISSUE THREAD

**Issue by LightDisTressEd** [SplashCodes/JAViewer#54]
Build version: 1.3.2 
Build date: 1979-11-30 00:00:00 
Current date: 2017-05-10 10:47:35 
Device: Meizu PRO 5 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.javiewer/io.github.javiewer.activity.GalleryActivity}: android.view.InflateException: Binary XML file line #15: Can't convert value at index 4 to dimension: type=0x4
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2699)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
Caused by: android.view.InflateException: Binary XML file line #15: Can't convert value at index 4 to dimension: type=0x4
Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 4 to dimension: type=0x4
	at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:720)
	at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:7243)
	at android.widget.FrameLayout$LayoutParams.<init>(FrameLayout.java:439)
	at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:370)
	at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:369)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:860)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
	at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
	at io.github.javiewer.activity.GalleryActivity.onCreate(GalleryActivity.java:118)
	at android.app.Activity.performCreate(Activity.java:6684)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2652)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2766)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1507)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6236)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)

**Comment by SplashCodes** [comment]
#52 已修复，release页的apk已更新
