### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by 1357209470** [SplashCodes/JAViewer#65]
Build version: 1.3.2 
Build date: 1979-11-30 00:00:00 
Current date: 2017-06-24 00:24:35 
Device: OnePlus A0001 
 
Stack trace:  
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 560608 bytes
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3810)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
Caused by: android.os.TransactionTooLargeException: data parcel size 560608 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(Binder.java:615)
	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3636)
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3802)
	... 7 more

**Comment by 1357209470** [comment]
按类别查看 放尿 番号 dep-001
