### ISSUE TITLE
切换任务崩溃

### ISSUE THREAD

**Issue by CodeFarmer1995** [SplashCodes/JAViewer#67]
Build version: 1.3.2 
Build date: 1979-11-30 00:00:00 
Current date: 2017-06-28 12:56:50 
Device: ZUK Z1 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke interface method 'retrofit2.Call io.github.javiewer.network.BasicService.get(java.lang.String)' on a null object reference
	at io.github.javiewer.fragment.MovieListFragment.newCall(MovieListFragment.java:27)
	at io.github.javiewer.fragment.MovieFragment$2.newCall(MovieFragment.java:47)
	at io.github.javiewer.view.listener.BasicOnScrollListener.onLoad(BasicOnScrollListener.java:71)
	at io.github.javiewer.view.listener.BasicOnScrollListener.refresh(BasicOnScrollListener.java:66)
	at io.github.javiewer.fragment.MovieFragment$1.onRefresh(MovieFragment.java:40)
	at io.github.javiewer.fragment.MovieFragment$3.run(MovieFragment.java:86)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5477)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

_Sent from my ZUK Z1 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by SplashCodes** [comment]
后台把静态变量回收了，请检查后台内存限制
