### ISSUE TITLE
以前的收藏都无效了，希望修复

### ISSUE THREAD

**Issue by yeluonight** [SplashCodes/JAViewer#82]
虽然收藏里还在，但是直接搜会发现变成没收藏的了，而且收藏的女优点开都没有作品，得重新搜索再收藏才行，还有就是，这样再收藏一次，之前的还在（比如我收藏了吉泽明步，但是点不开，重新收藏，收藏里会有两个吉泽明步）

**Comment by yeluonight** [comment]
刚发现点开以前收藏的作品，转圈几次然后会报错，错误信息如下：
Build version: 1.3.2 
Build date: 1979-11-30 00:00:00 
Current date: 2017-09-07 23:56:27 
Device: LeMobile Le X620 
 
Stack trace:  
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.jsoup.nodes.Element.text()' on a null object reference
	at io.github.javiewer.network.provider.AVMOProvider.parseMoviesDetail(AVMOProvider.java:77)
	at io.github.javiewer.activity.MovieActivity$2.onResponse(MovieActivity.java:115)
	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:5966)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)

**Comment by SplashCodes** [comment]
@2042460161 源站针对被墙问题进行了，更新，稍后软件也将更新。

**Comment by wufakanqingweilai** [comment]
期待更新

**Comment by SplashCodes** [comment]
@wufakanqingweilai 已更新，close #75, close #80, close #82
